name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Check Types
        run: deno task check

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Test publish
        run: deno task publish --dry-run

      - name: Run tests
        run: deno task test
